package com.hubu.dao;

import com.hubu.model.Superiortask;
import com.hubu.model.SuperiortaskExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SuperiortaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    long countByExample(SuperiortaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    int deleteByExample(SuperiortaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    int deleteByPrimaryKey(Integer initiatingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    int insert(Superiortask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    int insertSelective(Superiortask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    List<Superiortask> selectByExample(SuperiortaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    Superiortask selectByPrimaryKey(Integer initiatingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") Superiortask record, @Param("example") SuperiortaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    int updateByExample(@Param("record") Superiortask record, @Param("example") SuperiortaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    int updateByPrimaryKeySelective(Superiortask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superiortask
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    int updateByPrimaryKey(Superiortask record);
}