package com.hubu.model;

public class Superiortask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superiortask.initiatingId
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    private Integer initiatingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superiortask.initiatingdevice
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    private String initiatingdevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superiortask.targetdevice
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    private String targetdevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superiortask.issuedpath
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    private String issuedpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superiortask.tasktype
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    private String tasktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superiortask.taskname
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    private String taskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superiortask.taskdetails
     *
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    private String taskdetails;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superiortask.initiatingId
     *
     * @return the value of superiortask.initiatingId
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public Integer getInitiatingid() {
        return initiatingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superiortask.initiatingId
     *
     * @param initiatingid the value for superiortask.initiatingId
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public void setInitiatingid(Integer initiatingid) {
        this.initiatingid = initiatingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superiortask.initiatingdevice
     *
     * @return the value of superiortask.initiatingdevice
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public String getInitiatingdevice() {
        return initiatingdevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superiortask.initiatingdevice
     *
     * @param initiatingdevice the value for superiortask.initiatingdevice
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public void setInitiatingdevice(String initiatingdevice) {
        this.initiatingdevice = initiatingdevice == null ? null : initiatingdevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superiortask.targetdevice
     *
     * @return the value of superiortask.targetdevice
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public String getTargetdevice() {
        return targetdevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superiortask.targetdevice
     *
     * @param targetdevice the value for superiortask.targetdevice
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public void setTargetdevice(String targetdevice) {
        this.targetdevice = targetdevice == null ? null : targetdevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superiortask.issuedpath
     *
     * @return the value of superiortask.issuedpath
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public String getIssuedpath() {
        return issuedpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superiortask.issuedpath
     *
     * @param issuedpath the value for superiortask.issuedpath
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public void setIssuedpath(String issuedpath) {
        this.issuedpath = issuedpath == null ? null : issuedpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superiortask.tasktype
     *
     * @return the value of superiortask.tasktype
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public String getTasktype() {
        return tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superiortask.tasktype
     *
     * @param tasktype the value for superiortask.tasktype
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public void setTasktype(String tasktype) {
        this.tasktype = tasktype == null ? null : tasktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superiortask.taskname
     *
     * @return the value of superiortask.taskname
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superiortask.taskname
     *
     * @param taskname the value for superiortask.taskname
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname == null ? null : taskname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superiortask.taskdetails
     *
     * @return the value of superiortask.taskdetails
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public String getTaskdetails() {
        return taskdetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superiortask.taskdetails
     *
     * @param taskdetails the value for superiortask.taskdetails
     * @mbg.generated Mon Mar 11 20:21:05 CST 2019
     */
    public void setTaskdetails(String taskdetails) {
        this.taskdetails = taskdetails == null ? null : taskdetails.trim();
    }
}